<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Trusthub
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace ShopMagicTwilioVendor\Twilio\Rest\Trusthub\V1;

use ShopMagicTwilioVendor\Twilio\Options;
use ShopMagicTwilioVendor\Twilio\Values;
abstract class ComplianceInquiriesOptions
{
    /**
     * @param string $notificationEmail The email address that approval status updates will be sent to. If not specified, the email address associated with your primary customer profile will be used.
     * @return CreateComplianceInquiriesOptions Options builder
     */
    public static function create(string $notificationEmail = \ShopMagicTwilioVendor\Twilio\Values::NONE) : \ShopMagicTwilioVendor\Twilio\Rest\Trusthub\V1\CreateComplianceInquiriesOptions
    {
        return new \ShopMagicTwilioVendor\Twilio\Rest\Trusthub\V1\CreateComplianceInquiriesOptions($notificationEmail);
    }
}
class CreateComplianceInquiriesOptions extends \ShopMagicTwilioVendor\Twilio\Options
{
    /**
     * @param string $notificationEmail The email address that approval status updates will be sent to. If not specified, the email address associated with your primary customer profile will be used.
     */
    public function __construct(string $notificationEmail = \ShopMagicTwilioVendor\Twilio\Values::NONE)
    {
        $this->options['notificationEmail'] = $notificationEmail;
    }
    /**
     * The email address that approval status updates will be sent to. If not specified, the email address associated with your primary customer profile will be used.
     *
     * @param string $notificationEmail The email address that approval status updates will be sent to. If not specified, the email address associated with your primary customer profile will be used.
     * @return $this Fluent Builder
     */
    public function setNotificationEmail(string $notificationEmail) : self
    {
        $this->options['notificationEmail'] = $notificationEmail;
        return $this;
    }
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString() : string
    {
        $options = \http_build_query(\ShopMagicTwilioVendor\Twilio\Values::of($this->options), '', ' ');
        return '[Twilio.Trusthub.V1.CreateComplianceInquiriesOptions ' . $options . ']';
    }
}
