<?php

/**
 * This code was generated by
 * ___ _ _ _ _ _    _ ____    ____ ____ _    ____ ____ _  _ ____ ____ ____ ___ __   __
 *  |  | | | | |    | |  | __ |  | |__| | __ | __ |___ |\ | |___ |__/ |__|  | |  | |__/
 *  |  |_|_| | |___ | |__|    |__| |  | |    |__] |___ | \| |___ |  \ |  |  | |__| |  \
 *
 * Twilio - Flex
 * This is the public Twilio REST API.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace ShopMagicTwilioVendor\Twilio\Rest\FlexApi\V1\Interaction\InteractionChannel;

use ShopMagicTwilioVendor\Twilio\Options;
use ShopMagicTwilioVendor\Twilio\Values;
abstract class InteractionChannelParticipantOptions
{
    /**
     * @param array $routingProperties Object representing the Routing Properties for the new Participant.
     * @return CreateInteractionChannelParticipantOptions Options builder
     */
    public static function create(array $routingProperties = \ShopMagicTwilioVendor\Twilio\Values::ARRAY_NONE) : \ShopMagicTwilioVendor\Twilio\Rest\FlexApi\V1\Interaction\InteractionChannel\CreateInteractionChannelParticipantOptions
    {
        return new \ShopMagicTwilioVendor\Twilio\Rest\FlexApi\V1\Interaction\InteractionChannel\CreateInteractionChannelParticipantOptions($routingProperties);
    }
}
class CreateInteractionChannelParticipantOptions extends \ShopMagicTwilioVendor\Twilio\Options
{
    /**
     * @param array $routingProperties Object representing the Routing Properties for the new Participant.
     */
    public function __construct(array $routingProperties = \ShopMagicTwilioVendor\Twilio\Values::ARRAY_NONE)
    {
        $this->options['routingProperties'] = $routingProperties;
    }
    /**
     * Object representing the Routing Properties for the new Participant.
     *
     * @param array $routingProperties Object representing the Routing Properties for the new Participant.
     * @return $this Fluent Builder
     */
    public function setRoutingProperties(array $routingProperties) : self
    {
        $this->options['routingProperties'] = $routingProperties;
        return $this;
    }
    /**
     * Provide a friendly representation
     *
     * @return string Machine friendly representation
     */
    public function __toString() : string
    {
        $options = \http_build_query(\ShopMagicTwilioVendor\Twilio\Values::of($this->options), '', ' ');
        return '[Twilio.FlexApi.V1.CreateInteractionChannelParticipantOptions ' . $options . ']';
    }
}
